using OrderService.DTO.OrderItem;
using OrderService.Entities;
using System.ComponentModel.DataAnnotations;

namespace OrderService.DTO.Order
{
    public class CreateOrderDTO
    {
        public int IdUser { get; set; } // only admin

        
        public OrderStatus OrderStatus { get; set; } // only admin

        [Range(0, 100000)]
        public decimal TotalPrice { get; set; } // autogenerated

        [Required]
        public PaymentMethod PaymentMethod { get; set; } //null by default until paid?

 
        public DateTime CreatedAt { get; set; } // onyl admin

        [Required]
        public List<CreateOrderItemDTO> OrderItems { get; set; } = new List<CreateOrderItemDTO>();
    }
}
